prgrms-be-devcourse/NBE1_2_Team10

- application/src/main/java/core/application/reviews/exceptions/NoReviewCommentFoundException.java
- application/src/main/java/core/application/reviews/exceptions/NoReviewFoundException.java
- application/src/main/java/core/application/reviews/models/entities/ReviewCommentEntity.java
- application/src/main/java/core/application/reviews/models/entities/ReviewEntity.java
- application/src/main/java/core/application/reviews/services/ReviewCommentService.java
- application/src/main/java/core/application/reviews/services/ReviewCommentSortOrder.java
- application/src/main/java/core/application/reviews/services/ReviewService.java
- application/src/main/java/core/application/reviews/services/ReviewSortOrder.java
- `ReviewService` 관련된 베이스 코드를 작성한다.
- `ReviewService` 인터페이스 정의
- 주석 문서, 관련 `Exception` 추가
- `ReviewCommentSortOrder`, `ReviewSortOrder` 정렬 관련 enum 상수 추가
> `feat` : 리뷰 서비스 인터페이스를 만든다.

- application/build.gradle
- application/src/main/java/core/application/movies/Controller/MovieController.java
- application/src/main/java/core/application/movies/models/dto/MovieDetailRespDTO.java
- application/src/main/java/core/application/movies/service/MovieService.java
- application/src/main/java/core/application/movies/service/MovieServiceImpl.java
- application/src/main/resources/application.properties
KMDb API 예시 로직을 base code에 적용하였습니다.
[추가 사항]
1. kmdb key, url 추가 및 default.image 임시 경로 지정
2. json, WebFlux 설정 라이브러리 추가
3. MovieDetailRespDTO에 @Data 어노테이션 적용
4. MovieContoller, MovieServiceImpl 추가
[변경 사항]
1. MovieService 인터페이스에서 getMainPageMovieInfo, searchMovies 메소드 제거
> Feat/#25/movie detail - KMDb base code

- application/src/main/java/core/application/movies/models/entities/CachedMovieEntity.java
- application/src/main/java/core/application/movies/repositories/CachedMovieRepositoryImpl.java
- application/src/main/java/core/application/movies/repositories/mapper/CachedMovieMapper.java
- application/src/main/resources/application.properties
- application/src/main/resources/mappers/movies/CacheMovieMapper.xml
- application/src/test/java/core/application/movies/MovieRepositoryTest.java
이전 PR에서 수정할 부분이 있어서 수정하고 CachedMovieRepository 테스트 코드도 추가로 작성하였습니다.
- CachedMovieMapper 인터페이스 작성
- CachedMovieMapper xml 파일 작성
- CachedMovieRepository 구현
- application.properties에 Mybatis 설정 추가
- Mapper 인터페이스 save, update 반환 타입 수정
- 반환타입 변경에 따른 CachedMovieRepository 구현체 및 xml 수정
- CachedMovieEntity 찜, 리뷰, 한줄평 등록 및 삭제시 변경 기능 추가
save와 update의 반환 타입에 오류가 있어 수정하였습니다.
> Feat : CachedMovieRepository SQL 작성 및 구현

- application/src/main/java/core/application/users/mapper/DibMapper.java
- application/src/main/java/core/application/users/models/entities/UserEntity.java
- application/src/main/java/core/application/users/repositories/DibRepository.java
- application/src/main/java/core/application/users/repositories/DibRepositoryImpl.java
- application/src/main/resources/mappers/users/DibMapper.xml
찜 관련 SQL 구현
- DibRepositoryImpl 구현
- DibMapper 구현
- DIbMapper.xml 구현
- UserEntity : dibList, refreshToken 필드 삭제
> Feat : 찜 관련 SQL 구현

- application/src/main/java/core/application/config/WebClientConfig.java
- application/src/main/java/core/application/movies/controller/MovieController.java
- application/src/main/java/core/application/movies/models/dto/MainPageMovieRespDTO.java
- application/src/main/java/core/application/movies/models/dto/MainPageMoviesRespDTO.java
- application/src/main/java/core/application/movies/repositories/CachedMovieRepository.java
- application/src/main/java/core/application/movies/repositories/CachedMovieRepositoryImpl.java
- application/src/main/java/core/application/movies/repositories/mapper/CachedMovieMapper.java
- application/src/main/java/core/application/movies/service/MovieService.java
- application/src/main/java/core/application/movies/service/MovieServiceImpl.java
- application/src/main/resources/mappers/movies/CacheMovieMapper.xml
- application/src/test/java/core/application/movies/repository/MovieRepositoryTest.java
- application/src/test/java/core/application/movies/service/MovieServiceTest.java
메인페이지에 보여줘야 할 영화 목록을 제공하는 기능입니다.
보여주는 영화 목록은 다음과 같습니다.
- 찜 많은 순
- 평점 높은 순
- 리뷰 많은 순
- WebClient Bean 등록
- 리뷰 많은 순으로 보여주기 위한 Repository단 코드 작성
- 메인페이지 영화 목록 조회를 위한 서비스 구현
- 메인페이지 테스트 코드 작성
> Feat : 메인페이지 영화 목록 조회

- application/src/main/java/core/application/reviews/repositories/ReviewCommentRepository.java
- application/src/main/java/core/application/reviews/repositories/mybatis/MyBatisReviewCommentRepository.java
- application/src/main/java/core/application/reviews/repositories/mybatis/ReviewCommentMapperProvider.java
- application/src/main/java/core/application/reviews/services/ReviewCommentService.java
- application/src/main/java/core/application/reviews/services/ReviewCommentServiceImpl.java
- application/src/test/java/core/application/reviews/repositories/ReviewCommentRepositoryTest.java
- application/src/test/java/core/application/reviews/services/ReviewCommentServiceImplTest.java
- `ReviewCommentService` 구현체 작성
- 관련 테스트 코드 추가
---
Resolves: #38
> Feat/#38 - `ReviewCommentService` 구현체 추가

- application/src/main/java/core/application/users/mapper/DibMapper.java
- application/src/main/java/core/application/users/models/dto/DibRespDTO.java
- application/src/main/java/core/application/users/repositories/DibRepository.java
- application/src/main/java/core/application/users/repositories/DibRepositoryImpl.java
- application/src/main/java/core/application/users/service/DibService.java
- application/src/main/java/core/application/users/service/DibServiceImpl.java
- application/src/main/resources/mappers/users/DibMapper.xml
- application/src/test/java/core/application/users/repositories/DibRepositoryImplTest.java
- application/src/test/java/core/application/users/service/DibServiceImplTest.java
찜 관련 테스트 코드 작성
- DibRepository 테스트 코드 작성
* saveNewDib() : 찜 객체 반환하도록 수정
- DibService 테스트 코드 작성
** 현재 사용 중인 userId 불러오는 로직으로 수정 필요 **
> Feat : 찜 테스트 코드 작성

- application/src/main/java/core/application/reviews/ReviewExceptionHandler.java
- application/src/main/java/core/application/reviews/controllers/ReviewCommentController.java
- application/src/main/java/core/application/reviews/exceptions/InvalidCommentContentException.java
- application/src/main/java/core/application/reviews/exceptions/NotCommentOwnerException.java
- application/src/main/java/core/application/reviews/models/dto/request/CommonCommentReqDTO.java
- application/src/main/java/core/application/reviews/models/dto/request/CreateCommentReqDTO.java
- application/src/main/java/core/application/reviews/models/dto/request/EditCommentReqDTO.java
- application/src/main/java/core/application/reviews/models/dto/response/CommonCommentRespDTO.java
- application/src/main/java/core/application/reviews/models/dto/response/CreateCommentRespDTO.java
- application/src/main/java/core/application/reviews/models/dto/response/EditCommentRespDTO.java
- application/src/main/java/core/application/reviews/models/dto/response/MessageRespDTO.java
- application/src/main/java/core/application/reviews/models/dto/response/ShowCommentsRespDTO.java
- application/src/main/java/core/application/reviews/repositories/ReviewCommentRepository.java
- application/src/main/java/core/application/reviews/repositories/mapper/ReviewMapper.java
- application/src/main/java/core/application/reviews/repositories/mybatis/MyBatisReviewCommentRepository.java
- application/src/main/java/core/application/reviews/services/ReviewCommentService.java
- application/src/main/java/core/application/reviews/services/ReviewCommentServiceImpl.java
- application/src/test/java/core/application/reviews/repositories/ReviewCommentRepositoryTest.java
- application/src/test/java/core/application/reviews/services/ReviewCommentServiceImplTest.java
`후기 포스팅 댓글` 과 관련된 `ReviewCommentController` 를 구현하였습니다.
| `HTTP Method` | `URL` | `Query Param` | `기능` |
|:--:|:--|:--:|:--:|
| `GET` | `/movies/{movieId}/reviews/{reviewId}/comments` | `page` |부모 댓글 조회 (페이징) |
| `GET` | `/movies/{movieId}/reviews/{reviewId}/comments/{groupId}` | `page` |자식댓글 조회 (페이징) |
| `POST` | `/movies/{movieId}/reviews/{reviewId}/comments` |  |댓글 생성|
| `PATCH` | `/movies/{movieId}/reviews/{reviewId}/comments/{reviewCommentId}` |  |댓글 수정 |
| `DELETE` | `/movies/{movieId}/reviews/{reviewId}/comments` |  |댓글 삭제 |
| `PATCH` | `/movies/{movieId}/reviews/{reviewId}/comments` |  |좋아요 증감 |
---
1. 이전 만들었던 `ReviewCommentRepository` 관련 `SQL`, 인터페이스에 페이징 기능이 없어 추가하였습니다.
2. 각 `API` 에서 유저의 아이디가 필요한 경우, 추후 `Spring Security Context` 에서 제공받을 것이므로 임시 조치 하였습니다.
3. 같은 유저가 중복 `좋아요` 누르는 걸 …
> `Feat/#54/` - `후기 포스팅 댓글` 컨트롤러 구현

- application/src/main/resources/mappers/review/ReviewMapper.xml
- `ReviewMapper.xml` `mappers/review` 폴더로 이동
+ fix: 좋아요 `(like)` 컬럼 관련 typo 수정
- fixes: #60
> fix: `ReviewMapper` 위치 수정

- application/src/main/java/core/application/users/mapper/DibMapper.java
- application/src/main/resources/mappers/users/DibMapper.xml
> Hotfix : 마이페이지 버그 수정

- application/src/main/java/core/application/movies/service/MovieServiceImpl.java
- application/src/main/resources/application.properties
Merge 과정 중 삭제된 `defaultImgUrl`을 추가하고 properties 파일 내에 작성된 URL 지정 내용 위치를 수정하였습니다.
- `defaultImgUrl` 필드 추가
- 잘못 작성된 `@Value` 수정
- 기본 포스터 이미지 `private.properties`에 작성하도록 수정
> Hotfix : `MovieServiceImpl` 삭제된 필드 추가

- application/src/main/resources/application.properties
`application.properties`에 있던 `spring.profiles.active` 를 복구하였습니다. 이전에 이슈로 생성한 userId 관련 오류도 해당 부분에서 발생한 것으로 확인했습니다! `spring.profiles.active`이 내용이 `PrivateConfig`말고 `.properties` 파일을 추가하는 방법으로 할 때 사용하는 것으로 잘못알고 있어서 지워서 생긴 문제였습니다!
#75
> [Fix] : MybatisConfig 등록 설정 복구

- application/src/main/resources/application.properties
- assets/DDL.sql
Git commit history 정리 + 검토된 내용 복구하는 PR
- Resolves: #89
> fix: restore git history

- application/build.gradle
- application/src/main/java/core/application/config/SwaggerConfig.java
- application/src/main/java/core/application/movies/controller/CommentController.java
- application/src/main/java/core/application/movies/controller/MovieController.java
- application/src/main/java/core/application/movies/models/dto/CommentRespDTO.java
- application/src/main/java/core/application/movies/models/dto/CommentWriteReqDTO.java
- application/src/main/java/core/application/movies/models/dto/MainPageMovieRespDTO.java
- application/src/main/java/core/application/movies/models/dto/MainPageMoviesRespDTO.java
- application/src/main/java/core/application/movies/models/dto/MovieDetailRespDTO.java
- application/src/main/java/core/application/movies/models/dto/MovieSearchRespDTO.java
- application/src/main/java/core/application/reviews/controllers/ReviewCommentController.java
- application/src/main/java/core/application/reviews/models/dto/request/CommonCommentReqDTO.java
- application/src/main/java/core/application/reviews/models/dto/response/ShowCommentsRespDTO.java
- application/src/main/java/core/application/reviews/models/entities/ReviewCommentEntity.java
- application/src/main/resources/application.properties
`movies`와 `reviews` 도메인에 Swagger를 적용하였습니다. 컨트롤러와 DTO를 중심으로 적용하였습니다.
Swagger를 사용하다보니 컨트롤러 내에 Swagger 코드 비중이 점점 많아져 추후 리팩토링 과정에 여유가 된다면 커스텀 어노테이션을 생성하여 분리할 예정입니다.
`users` 도메인은 추후 컨트롤러 `develop` 브랜치에 Merge 시 구현하여 따로 PR 올리려고 합니다!
- Swagger 의존성 설정 및 `properties` 설정
- `SwaggerConfig` 파일 추가
- `CommentController` Swagger 적용
- `MovieController` Swagger 적용
- `ReviewCommentController` Swagger 적용
> [Docs] `movies`, `reviews` Swagger 적용

- application/src/main/java/core/application/users/controller/DibController.java
- application/src/main/java/core/application/users/controller/MyPageController.java
- application/src/main/resources/mappers/users/DibMapper.xml
마이페이지, 찜 컨트롤러 구현
- DibController 구현
- MyPageController 구현
- DibMapper.xml 수정(dib.movieId -> movieId)
> Feat : 마이페이지 찜 controller 구현

- README.md
README의 기초 형식 작성
프로젝트 개발 문서 작성을 위한 README 파일의 기초 형식 작성
이후 소은님과 파트 분배하여 작성 후 pr 예정
※ 하단의 프로젝트 담당 기능에 본인이 담당했던 기능 구현 사항 작성 부탁드립니다.
> Base README.md Update

- application/src/main/java/core/application/config/SecurityConfig.java
- application/src/main/java/core/application/users/controller/DibController.java
- application/src/main/java/core/application/users/controller/MyPageController.java
- application/src/main/java/core/application/users/controller/UserController.java
`user` 도메인 Swagger 적용하였습니다!
컨트롤러에 메서드가 많지 않아서 변경사항은 별로 없어요!
- `DibController`
- `MyPageController`
- `UserController`
> [Docs] `user` 도메인 Swagger 적용

- application/src/main/java/core/application/reviews/controllers/ImageUploadController.java
`ImageUploadController`에 Swagger를 적용했습니다!
CK Editor 응답은 ApiResponse로 하면 안될 것 같아 응답은 수정하지 않았습니다.
> [Docs] CkEditor Swagger 적용

- application/src/main/java/core/application/movies/exception/NotMatchMovieCommentException.java
예외 처리 과정 중 예외 클래스가 빠져있어서 생성하여 올렸습니다.
- `NotMatchMovieCommentException` 추가
> [Hotfix] `NotMatchMovieCommentException` 추가

- application/src/main/java/core/application/reviews/controllers/ReviewController.java
준상님이 구현하신 Review Controller에 `ApiResponse`와 `Swagger`를 적용하였습니다.
- 기존 반환 객체를 ApiResponse로 감싼 후 반환
- `Swagger` 적용
- 정해지지 않은 응답 형식에 대한 TODO 제거
> [Refactor] Review Controller `ApiResponse` 및 `Swagger` 적용

- README.md
현 프로젝트와 관련한 문서화 작업 진행
※ 하단의 프로젝트 담당 기능에 본인이 담당했던 기능 구현 사항 작성 부탁드립니다.
> README 1차 초안 작성

- application/src/main/java/core/application/users/controller/DibController.java
- application/src/main/java/core/application/users/controller/MyPageController.java
- application/src/main/java/core/application/users/service/DibService.java
- application/src/main/java/core/application/users/service/DibServiceImpl.java
- application/src/main/resources/mappers/users/UserMapper.xml
마이페이지, 찜 리팩토링
- userId 불러오는 로직 추가
- UserMapper에서 selectDibsOnUserId() 삭제
- DibMapper의 saveNewDib에서 useGeneratedKey 설정 삭제
- cached_movie_table에 찜하려는 영화 없을 경우 API에서 불러와서 cached_movie_table에 따로 저장한 뒤에 찜하기 로직 수행하도록 변경
> Refactor : 마이페이지, 찜 리팩토링

- application/src/main/java/core/application/config/SecurityConfig.java
- application/src/main/java/core/application/reviews/controllers/ReviewCommentController.java
- application/src/main/java/core/application/reviews/controllers/ReviewController.java
- assets/DDL.sql
- `Query param` 비어있을 때 `handel` 추가
- `Review Table` `DDL`수정
- 포스팅 리뷰 생성 시 `Connection is read only` 에러 해결
- `/error` `URL` 권한 요구 해제
---
- fixes: #103 
- fixes: #119
> Hotfix/#199 - `Review`, `Review Comment` 관련 버그 수정

- application/src/main/java/core/application/users/controller/UserController.java
- application/src/main/java/core/application/users/models/dto/UserRequestDTO.java
- application/src/main/java/core/application/users/service/UserService.java
- application/src/main/java/core/application/users/service/UserServiceImpl.java
사용자 회원 가입, 회원 정보 수정 시 사용할 UserRequestDTO 생성
사용자 회원 가입, 회원 정보 수정 시 사용할 UserRequestDTO 생성하고 관련 파트 수정
사용자 회원 가입, 회원 정보 수정 시 필수로 입력해야 할 데이터를 잘 모르겠으므로 새로운 요청 DTO가 있으면 좋겠음
#108
> Hotfix : 추가 userReqDTO

- application/src/main/java/core/application/users/models/dto/UserRequestDTO.java
- application/src/main/java/core/application/users/service/UserServiceImpl.java
> Hotfix/resolve -  `build` 시 `compile error` 안 나도록 수정

- application/src/main/java/core/application/reviews/controllers/ReviewCommentController.java
- application/src/main/java/core/application/reviews/controllers/ReviewController.java
- application/src/main/java/core/application/reviews/repositories/ReviewRepository.java
- application/src/main/java/core/application/reviews/repositories/mybatis/MyBatisReviewRepository.java
- application/src/main/java/core/application/reviews/repositories/mybatis/mappers/ReviewMapper.java
- application/src/main/java/core/application/reviews/services/ReviewService.java
- application/src/main/java/core/application/reviews/services/ReviewServiceImpl.java
- application/src/main/resources/mappers/review/ReviewCommentMapper.xml
- application/src/main/resources/mappers/review/ReviewMapper.xml
- application/src/test/java/core/application/reviews/repositories/ReviewCommentRepositoryTest.java
- application/src/test/java/core/application/reviews/repositories/ReviewRepositoryTest.java
`ReviewController`, `ReviewCommentController` 에서 `List< ... >` 형태의 응답을
`Page< ... >` 형태로 변경하였습니다.
---
복잡성을 낮추기 위해 `Service`, `Repository` 계층의 `List< ... >` 는 수정하지 않고,
`Controller` 계층에서 `Page` 객체를 생성해 응답하였습니다.
---
- Resolves : #147
> Refactor/#147 - `Review` 관련 응답 형태 `Page` 로 변경

- application/src/main/java/core/application/filter/JWTFilter.java
conflict resolving하면서 들어가게 된 쓸모없는 코드 삭제
conflict resolving하면서 들어가게 된 쓸모없는 코드 삭제
> Refactor : 삭제 불필요한 코드

- application/src/main/java/core/application/movies/models/dto/response/CommentRespDTO.java
CommentRespDTO 필드명 변경
- content > cmtContent 수정
> [refactor] CommentRespDTO 필드명 변경

- application/src/main/java/core/application/users/service/UserServiceImpl.java
user update 기능 수정
userUpdate 로직 수정
mybatis에서 jpa로 변경하게 되면서 dto에 null이 들어가더라도 자동으로
되게 되어있던 것이 제대로 반영이되지 않고 SQLException 문제 해결
> [Bugfix] 수정 user update

- application/src/main/java/core/application/filter/JWTFilter.java
- application/src/main/java/core/application/security/token/TokenService.java
잘못된 inactive rt 로직 수정
잘못된 inactive rt 로직 수정
> [Bugfix] : 수정 inactive rt 로직

- application/src/test/java/core/application/users/service/UserServiceImplTest.java
잘못 작성된 userService test 코드 리팩토링
mock을 사용한 userService test 코드 리팩토링
서비스 테스트에 맞게 테스트 코드 수정
> [Refactor] userService test 코드 리팩토링

- application/src/test/java/core/application/users/service/UserServiceImplTest.java
This reverts commit b32c12be234fdc4d1a45cd999ed6514eae3932bc.
> Revert "Refactor : userService test 코드 리팩토링"

- application/src/test/java/core/application/users/service/UserServiceImplTest.java
user Service 테스트 리팩토링
user Service 테스트 리팩토링
> [Refactor] user service test 리팩토링

- application/src/test/java/core/application/users/service/UserServiceImplTest.java
> develop -> main

- application/src/test/java/core/application/users/service/UserServiceImplTest.java
bugfix : merge conflict 해결 시 잘못된 코드 수정
> bugfix : merge conflict 해결 시 잘못된 코드 수정

- application/src/test/java/core/application/users/service/UserServiceImplTest.java
> bugfix : merge conflict 해결 시 잘못된 코드 수정 develop -> main
